trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-build-vars

steps:
- bash: |
    var_value=$(./var_value_get_REST.sh host/client/node1 $(client-node1-api-key) secrets/db-username)
    echo "Secret retrieved is: $(var_value)"
