pool: NewPool

variables:
- group: build-vars-common
- group: build-vars-managed-id

steps:
- task: DownloadSecureFile@1
  name: conjurCert
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'conjur-dev.pem'

- bash: |
    cat $(conjurCert.secureFilePath) > $(CONJUR_CERT_FILE)
    export TF_VAR_BOT_NAME=$(./get_conjur_secret.sh $(CONJUR_AUTHN_LOGIN) $(botName) )
    export TF_VAR_BOT_TOKEN=$(./get_conjur_secret.sh $(CONJUR_AUTHN_LOGIN) $(botToken) )
    echo "Secrets retrieved:"
    echo "  botName: $TF_VAR_BOT_NAME" 
    echo "  botToken: $TF_VAR_BOT_TOKEN" 
    terraform apply
