pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-build-vars

steps:
- bash: |
    export DB_UNAME=$(./get_conjur_secret.sh host/client/node1 $(client-node1-api-key) secrets/db-username)
    export DB_PWD=$(./get_conjur_secret.sh host/client/node1 $(client-node1-api-key) secrets/db-password)
    echo "Secrets retrieved:"
    echo "  DB_UNAME: $DB_UNAME" 
    echo "  DB_PWD: $DB_PWD" 
