trigger:
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://jodytest.eastus.cloudapp.azure.com'
    conjuraccount: 'dev'
    conjurusername: 'host/client/node1'
    conjurapikey: '2ka3kd83szp9941j6d7a7vqc7s41xkc9221f3rhhz3n6z9jxm13g82'
    ignoreSsl: true
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-build-vars

steps:
- bash: |
    export DB_UNAME=$(./var_value_get_REST.sh host/client/node1 $(client-node1-api-key) secrets/db-username)
    export DB_PWD=$(./var_value_get_REST.sh host/client/node1 $(client-node1-api-key) secrets/db-password)
    echo "Secrets retrieved:"
    echo "  DB_UNAME: $DB_UNAME" 
    echo "  DB_PWD: $DB_PWD" 
