# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-build-vars

steps:
- script: ./var_value_get_REST.sh host/client/node1 $(client-node1-api-key) secrets/db-username

